version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:80"
    container_name: primeiro-projeto-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
